name: Default development pipeline

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: 8.0.x

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet tool restore

      - name: Build
        run: dotnet build --no-restore

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet tool restore

      - name: Check Formatting
        run: dotnet csharpier --check .

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet tool restore

      - name: Install EF Core CLI
        run: dotnet tool install dotnet-ef --global

      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.2.0
        with:
          catalog: alpimi
          connection-string-env-var: TEST_CONNECTION_STRING

      - name: Database migration
        run: |
          dotnet ef migrations script --idempotent -o tmp/db.sql
          sqlcmd -d "alpimi" -i tmp/db.sql

      - name: Run unit and integration tests
        run: dotnet test --verbosity normal
